apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ciklum-devops8953-pp-ua-tls
spec:
  secretName: ciklum-devops8953-pp-ua
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ciklum-devops8953.pp.ua
  dnsNames:
    - ciklum-devops8953.pp.ua
    - www.ciklum-devops8953.pp.ua
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ciklum-devops8953.pp.ua
          - www.ciklum-devops8953.pp.ua